// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Task1.Models
{
    public partial class pubsContext : DbContext
    {
        public pubsContext()
        {
        }

        public pubsContext(DbContextOptions<pubsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<employee> employees { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=pubs;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<employee>(entity =>
            {
                entity.HasKey(e => e.emp_id)
                    .HasName("PK_emp_id")
                    .IsClustered(false);

                entity.HasIndex(e => new { e.lname, e.fname, e.minit }, "employee_ind")
                    .IsClustered();

                entity.Property(e => e.emp_id).IsFixedLength();

                entity.Property(e => e.hire_date).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.job_id).HasDefaultValueSql("((1))");

                entity.Property(e => e.job_lvl).HasDefaultValueSql("((10))");

                entity.Property(e => e.minit).IsFixedLength();

                entity.Property(e => e.pub_id)
                    .HasDefaultValueSql("('9952')")
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}