USE [master]
GO

/****** Object:  Database [ITI]    Script Date: 1/1/2023 10:51:31 PM ******/
CREATE DATABASE [ITI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ITI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ITI.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ITI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ITI_log.ldf' , SIZE = 6272KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ITI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ITI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ITI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ITI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ITI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ITI] SET ARITHABORT OFF 
GO

ALTER DATABASE [ITI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ITI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ITI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ITI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ITI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ITI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ITI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ITI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ITI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ITI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ITI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ITI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ITI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ITI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ITI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ITI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ITI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ITI] SET RECOVERY FULL 
GO

ALTER DATABASE [ITI] SET  MULTI_USER 
GO

ALTER DATABASE [ITI] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [ITI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ITI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ITI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ITI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ITI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ITI] SET  READ_WRITE 
GO

