// <auto-generated />
namespace Customers_with_orders.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adddataannotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddataannotation));
        
        string IMigrationMetadata.Id
        {
            get { return "202303141026429_add-data-annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
